apiVersion: 1
datasources: 
  - name: telemetry
    type: mssql
    database: telemetry
    url: sqledge:1433
    isDefault: true
    editable: true
    user: sa
    secureJsonData:
      password: "Pariveda@123!"