{
 "title": "Beckhoff Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch([SERVER_TIMESTAMP]),\n  [VALUE] as [value]\nFROM\n  [dbo].[DEVICE_DATA]\nWHERE\n  $__timeFilter([SERVER_TIMESTAMP]) and [NODE_ID] = 'nsu=KEPServerEX;s=Beckhoff.TF6100.PLC1.MAIN.nFan'\nORDER BY\n  [SERVER_TIMESTAMP] ASC"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch([SERVER_TIMESTAMP]),\n  [VALUE] as value\nFROM\n  [dbo].[DEVICE_DATA]\nWHERE\n  $__timeFilter([SERVER_TIMESTAMP]) and NODE_ID = 'nsu=KEPServerEX;s=Beckhoff.TF6100.PLC1.MAIN.nTemperature'\nORDER BY\n  [SERVER_TIMESTAMP] ASC"
    }
   ]
  },
  {
   "title": "Lamp Runtime",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch([SERVER_TIMESTAMP]),\n  CASE WHEN [VALUE] = 1 THEN 'ON' ELSE 'OFF' END as value\nFROM\n  [dbo].[DEVICE_DATA]\nWHERE\n  $__timeFilter([SERVER_TIMESTAMP]) and NODE_ID = 'nsu=KEPServerEX;s=Beckhoff.TF6100.PLC1.MAIN.bLamp'\nORDER BY\n  SERVER_TIMESTAMP ASC"
    }
   ]
  }
 ]
}